name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build static site
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_BASE_PATH: attack-vector
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Next.js app
        run: pnpm build

      - name: Disable Jekyll on GitHub Pages
        run: touch out/.nojekyll

      - name: Scope paths to repository subdirectory
        env:
          BASE_PATH: ${{ env.NEXT_PUBLIC_BASE_PATH }}
        run: |
          if [ -n "$BASE_PATH" ]; then
            find out \( -name '*.html' -o -name '*.txt' -o -name '*.json' \) -type f -print0 |
              xargs -0 perl -pi -e 's|(href|src)="\/(?!\/)|$1="/'"$BASE_PATH"'\/|g'
          fi

      - name: Add redirect for repository URL
        env:
          BASE_PATH: ${{ env.NEXT_PUBLIC_BASE_PATH }}
        run: |
          mkdir -p "out/${BASE_PATH}"
          cat <<'HTML' > out/attack-vector/index.html
          <!DOCTYPE html>
          <html lang="en">
            <head>
              <meta http-equiv="Refresh" content="0; url=https://attack-vector.com/" />
              <meta charset="utf-8" />
              <title>Redirecting…</title>
            </head>
            <body>
              <p>Redirecting to <a href="https://attack-vector.com/">attack-vector.com</a>…</p>
              <script>
                window.location.replace("https://attack-vector.com/");
              </script>
            </body>
          </html>
          HTML

      - name: Move site under subdirectory
        env:
          BASE_PATH: ${{ env.NEXT_PUBLIC_BASE_PATH }}
        run: |
          mkdir -p "out/${BASE_PATH}"
          shopt -s dotglob
          for entry in out/*; do
            name="$(basename "$entry")"
            if [ "$name" = "${BASE_PATH}" ] || [ "$name" = "CNAME" ] || [ "$name" = ".nojekyll" ]; then
              continue
            fi
            mv "$entry" "out/${BASE_PATH}/"
          done
          shopt -u dotglob

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
